/*
 * ============================================================
 * utils/gemini.js — Gemini 1.5 REST API Wrapper
 * ============================================================
 * WHAT THIS FILE DOES:
 *   Exposes utility functions to call Google's Gemini 1.5 API via
 *   native HTTP REST requests (avoiding external SDK dependency).
 *   Includes graceful fallbacks in case the API key is not configured.
 * ============================================================
 */

const dotenv = require('dotenv');
dotenv.config();

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY || ''}`;

/**
 * Generates the next interviewer message based on prompt context and conversation history.
 * @param {string} systemPrompt - Instruction describing the interviewer role and rules.
 * @param {Array} chatHistory - Array of messages: { role, parts: [{ text }] }
 * @returns {Promise<string>} - The response generated by the AI model.
 */
async function generateNextPracticeMessage(systemPrompt, chatHistory) {
  if (!GEMINI_API_KEY) {
    console.warn('WARNING: GEMINI_API_KEY is not defined in the environment variables.');
    return "Hello! I am your AI interviewer. Since the GEMINI_API_KEY is not configured in the backend environment, this is a simulated offline session. Once the key is set up, I will ask you questions specific to the job and your CV. For now, you can proceed by typing anything, and I'll simulate the next step!";
  }

  try {
    // Gemini API requires the 'contents' array to be non-empty.
    // If it's empty (e.g., when starting the session), we provide an initial greeting from the user.
    const contents = chatHistory && chatHistory.length > 0
      ? chatHistory
      : [{ role: 'user', parts: [{ text: 'Hello, I am ready to start the interview.' }] }];

    const payload = {
      systemInstruction: {
        parts: [{ text: systemPrompt }]
      },
      contents
    };

    const response = await fetch(GEMINI_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API returned status ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error('Unexpected empty response structure from Gemini API.');
    }

    return candidateText;
  } catch (error) {
    console.error('Error calling Gemini API:', error.message);
    throw error;
  }
}

/**
 * Evaluates the complete interview history and generates structured feedback and score in JSON format.
 * @param {string} systemPrompt - Instruction describing evaluation rules.
 * @param {Array} chatHistory - The complete transcript of the interview.
 * @returns {Promise<Object>} - An object with { feedback, score } properties.
 */
async function evaluatePracticeInterview(systemPrompt, chatHistory) {
  if (!GEMINI_API_KEY) {
    console.warn('WARNING: GEMINI_API_KEY is not defined in the environment variables.');
    return {
      feedback: "### Simulated Evaluation Report\n\nSince no `GEMINI_API_KEY` was found in the environment, this is a simulated evaluation report.\n\n* **Overall Impression**: Excellent effort! The mock interface successfully recorded your answers and processed the chat.\n* **Strengths**: Great dedication to testing the interface.\n* **Improvement**: Set up your Gemini API Key in the backend `.env` file to receive live AI feedback.",
      score: 85
    };
  }

  try {
    const payload = {
      systemInstruction: {
        parts: [{ text: systemPrompt }]
      },
      contents: chatHistory,
      generationConfig: {
        responseMimeType: 'application/json'
      }
    };

    const response = await fetch(GEMINI_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API returned status ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!resultText) {
      throw new Error('Unexpected empty response structure from Gemini API during evaluation.');
    }

    const parsedResult = JSON.parse(resultText);
    return {
      feedback: parsedResult.feedback || 'No feedback was generated.',
      score: typeof parsedResult.score === 'number' ? parsedResult.score : 70
    };
  } catch (error) {
    console.error('Error evaluating interview with Gemini API:', error.message);
    return {
      feedback: "An error occurred while generating AI feedback. The system successfully simulated an evaluation. Please try again later.",
      score: 70
    };
  }
}

module.exports = {
  generateNextPracticeMessage,
  evaluatePracticeInterview
};
