/*
 * ============================================================
 * models/PracticeInterview.js — AI Practice Interview Model
 * ============================================================
 * WHAT THIS FILE DOES:
 *   Defines the PracticeInterview schema and exports the model.
 *   Tracks simulated AI practice interviews conducted by candidates
 *   for specific applied jobs. Stored chat history uses a role/parts
 *   structure matching Gemini's API format.
 * ============================================================
 */

const mongoose = require('mongoose');

const practiceInterviewSchema = new mongoose.Schema(
  {
    // The candidate who is practicing
    candidate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Candidate is required']
    },

    // The job posting this practice is for
    job: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Job',
      required: [true, 'Job is required']
    },

    // The application linking the candidate and the job
    application: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Application',
      required: [true, 'Application is required']
    },

    /*
     * messages stores the chat history.
     * We use a structure of { role, parts: [{ text }] } to align
     * directly with Google Gemini's chat format requirements.
     */
    messages: [
      {
        role: {
          type: String,
          enum: ['user', 'model'],
          required: [true, 'Message role is required']
        },
        parts: [
          {
            text: {
              type: String,
              required: [true, 'Message text is required']
            }
          }
        ],
        timestamp: {
          type: Date,
          default: Date.now
        }
      }
    ],

    // Review/feedback generated by Gemini upon completing the practice
    feedback: {
      type: String,
      default: ''
    },

    // Evaluation score out of 100 generated by Gemini
    score: {
      type: Number,
      default: null
    },

    // Session status
    status: {
      type: String,
      enum: ['in_progress', 'completed'],
      default: 'in_progress'
    }
  },
  {
    timestamps: true
  }
);

// Compound index so that a candidate has at most one active/saved practice session per application.
practiceInterviewSchema.index({ candidate: 1, application: 1 }, { unique: true });

const PracticeInterview = mongoose.model('PracticeInterview', practiceInterviewSchema);

module.exports = PracticeInterview;
